### ISSUE TITLE
Some useful functions

### ISSUE THREAD

**Issue by zachhalle** [sdiehl/protolude#1]
While recognizing that deciding what to include and exclude is a difficult balancing act, I was wondering if there was a specific reason that forM/mapM are not included here? (Also, apologies if this is the wrong place to bring this up, I'm still trying to figure out github's interface)

**Comment by sdiehl** [comment]
They are included from `Data.Traversable`.  

https://github.com/sdiehl/protolude/blob/master/src/Protolude.hs#L67
