### ISSUE TITLE
traceShow has different type

### ISSUE THREAD

**Issue by alexanderkjeldaas** [sdiehl/protolude#10]
`Debug.Trace.traceShow` already exists with a different signature.

The Protolude one should probably use the same type if it exposes the same function name.

**Comment by sdiehl** [comment]
You want `traceShow :: Show a => a -> b -> b`?

**Comment by alexanderkjeldaas** [comment]
yes, at least that was what I needed to fix when converting over to Protolude.  I don't have a strong opinion on this, but there already exists a `traceShow` with that signature so it makes porting easier.
