### ISSUE TITLE
Haddocks are not very discoverable

### ISSUE THREAD

**Issue by juliapath** [sdiehl/protolude#104]
Currently the `Protolude` haddock is just one huge list. This is not very discoverable and it is impossible to see at a glimpse what kind of stuff is included. The only thing you can do is wait for the entire page to load which can already take some time and then test with Ctrl+F if some specific thing is there. I see two possible ways to improve this:

1. Split `Protolude` into a bunch of smaller modules and reexport them (in a way that they are displayed as reexports in the Haddocks).
2. Use headings in the Haddock. This does not fix the long loading time and the huge page would still be rather unhandy but a table of contents would go a long way. See [RIO.Prelude](https://hackage.haskell.org/package/rio-0.1.9.2/docs/RIO-Prelude.html) and [RIO.Prelude.Types](https://hackage.haskell.org/package/rio-0.1.9.2/docs/RIO-Prelude-Types.html) for an example.

I also noticed that while `RIO.Prelude` loads almost instantly, `RIO.Prelude.Types` takes some time to load, so doing this (splitting all the types and type classes into a different module) may also help with the loading time. Though I'm not sure if I like this segregation of types and type classes from values.

**Comment by sdiehl** [comment]
Closed as of 0.3 refactor to Haddock docs.
