### ISSUE TITLE
Missing `Symbols.md` file

### ISSUE THREAD

**Issue by asterite** [sdiehl/protolude#105]
The readme [mentions](https://github.com/sdiehl/protolude#exported-functions) that exported functions can be seen in a `Symbols.md` file but it seems it's no longer there.

Where can one see all the exported symbols?

Thank you!

**Comment by sdiehl** [comment]
Haddock fixed a long standing bug that allows Hackage to display all exported symbols now. So Symbols.md is no longer needed.

http://hackage.haskell.org/package/protolude-0.2.3/docs/Protolude.html

**Comment by asterite** [comment]
Cool, thanks! I will send a PR to fix the link in the readme to point to haddock.
