### ISSUE TITLE
Generate a list of everything Protolude exports

### ISSUE THREAD

**Issue by seagreen** [sdiehl/protolude#112]
I think this would be useful for people considering Protolude, and also for writing changelog entries and making sure no exports slip through that we don't want.

A quick way to get started is `echo :browse Protolude | stack ghci > exported.txt`. I've pushed up a branch to my fork showing what that looks like: https://github.com/seagreen/protolude/commit/000bc22f348f78143824260233bbeaf234b40c44

However, it takes some post-processing to remove the "[ 1 of 19] Compiling Protolude.Safe" lines.

Additionally it's not in alphabetical order. Since it prints more info than just identifiers (eg type signatures, sometimes split over multiple lines) getting it into alphabetical order will take a little work.

Do you think an export list would be a good thing to have? If so we can talk more about whether processing the output of `:browse` is the best path towards it, or if there's a better way.

**Comment by sdiehl** [comment]
This is a great idea. Maybe we should also have this auto generated by and under version control. It will vary based on the version of Base and GHC though as the underlying exports grow as base version increases.

**Comment by sdiehl** [comment]
Dumping it out through GHCi is probably not the right way to do this, just too much noise from all the printed defs. Probably the right way is to extract the symbol list (`availNames`) out of interface via the exports list [mi_exports](https://hackage.haskell.org/package/ghc-8.6.5/docs/HscTypes.html#t:ModIface). Can see the whole export list if you use `--show-iface` on `Protolude.hi`. This is how I did it originally. 

Can probably make a small script to read the iface file and then across the different ghc base versions can export those to a file.

**Comment by sdiehl** [comment]
This should be a nice solution to this issue.
https://github.com/protolude/protolude/pull/114/files

**Comment by seagreen** [comment]
Awesome!
