### ISSUE TITLE
Release 0.3.0 to hackage?

### ISSUE THREAD

**Issue by robx** [sdiehl/protolude#116]
On the off-chance that you merely forgot to upload the new version, I wanted to suggest doing that.

(I ran up against the protolude 0.2.4 base upper bound while trying to update a package of mine for GHC 8.10. Worked around that for now by getting protolude from git, so it's no big issue for me currently.)

**Comment by sdiehl** [comment]
It will get released soon, just doing some final testing on some downstream packages.

**Comment by sdiehl** [comment]
The release candidate is cut if you fancy trying it out. I'll upload the final package in the next day or so.

https://hackage.haskell.org/package/protolude-0.3.0/candidate
https://hackage.haskell.org/package/protolude-0.3.0/candidate/docs/Protolude.html

**Comment by robx** [comment]
Works great for me, i.e., my package builds fine via cabal and ghc 8.10 after unpacking the release candidate archive. Thanks!

**Comment by jberryman** [comment]
Thanks @sdiehl! would you mind releasing now? Also I wasn't aware of the package candidates feature

**Comment by jchia** [comment]
Does anyone know how to specify the candidate version 0.3.0 in cabal.project? Is it possible?

**Comment by robx** [comment]
@jchia My understanding was that you can't get cabal to download the candidate version, but unpacking the source archive at your project top-level will make cabal use it by default (via the [optional-packages](https://cabal.readthedocs.io/en/latest/cabal-project.html#cfg-field-optional-packages) field in `cabal.project`).

**Comment by sdiehl** [comment]
Upload is complete.
https://hackage.haskell.org/package/protolude-0.3.0
