### ISSUE TITLE
isSuffixOf to accompany isPrefixOf

### ISSUE THREAD

**Issue by jchia** [sdiehl/protolude#119]
Currently, `Protolude` reexports `isPrefixOf` from `Data.List`. What about also re-exporting `isSuffixOf`, and maybe `isInfixOf`?

**Comment by adamwespiser** [comment]
Implemented in: https://github.com/protolude/protolude/commit/1b453b60645faf44820d8cb841755e5f20ac1d11

Should be released in `0.3.1`
