### ISSUE TITLE
Using printf rather than formatting

### ISSUE THREAD

**Issue by kqr** [sdiehl/protolude#12]
Hey, I'm mostly curious if there's a specific reason you've included printf instead of formatting. The main benefit I can see with formatting are that formats are composable. (Putting this publicly as an issue rather than in a private email for the benefit of future readers!)

One drawback of printf is that it only returns `String`s, which are banned. Similar thing goes for choosing to keep in `readMaybe` and friends without converting to `Text`.

**Comment by sdiehl** [comment]
Yeah, printf is going to get removed in the next version. 

The Read/Show solution is something I'm working on at the moment, but being able auto-derive these in terms of Text is non-trivial and will require a bit of work.

**Comment by sdiehl** [comment]
Printf is now removed in 0.1.6. I think a dependency on 'formatting' is a bit heavy and probably should be an opt-in rather than something provided by this library.
