### ISSUE TITLE
Documentation: Gap in link on Hackage 

### ISSUE THREAD

**Issue by ShalokShalom** [sdiehl/protolude#122]
See [this part of the description in your Hackage](https://hackage.haskell.org/package/protolude-0.3.0/#readme) doesnt render as HTML

![Screenshot_2021-03-04-17-51-07-14](https://user-images.githubusercontent.com/6344099/109999466-89388c80-7d12-11eb-8c35-5888c0a96c54.jpg)

The reason is, that there is a superfluous space inbetween:
```
[Haskell antipattern]( http://www.stephendiehl.com/posts/strings.html)
```

**Comment by adamwespiser** [comment]
fixed in above PR
