### ISSUE TITLE
Add missing Git tags for versions 0.3.0, 0.3.1, and 0.3.2

### ISSUE THREAD

**Issue by cs** [sdiehl/protolude#139]
Versions 0.3.0, 0.3.1, and 0.3.2 have all been [officially released](https://hackage.haskell.org/package/protolude), but they don't have a corresponding Git tag. Based on the commit messages, I believe the following revisions should be tagged ...

```sh
git tag -f 0.3.0 2666f1e
git tag -f 0.3.1 3e24972
git tag -f 0.3.2 e40b735
```

... and, of course, pushed to GitHub:

```sh
git push --tags origin
```

**Comment by cs** [comment]
`git tag -f 0.3.0 2666f1e` can't be correct after all, because Stack LTS 18.x includes [protolude-0.3.0](https://www.stackage.org/lts-18.28/package/protolude-0.3.0) and [base-4.14.3.0](https://www.stackage.org/lts-18.28/package/base-4.14.3.0). However, revision 2666f1e83007ccd76ef4f2f839d5dd053d85d783 still has the incompatible dependency `base >= 4.6  && <4.14` and therefore can't be right.

**Comment by adamwespiser** [comment]
I didn't do the `3.0` release, but checking out several commits and looking at version bounds as well as the change log, it appears that `22e2cec` is what we want for `3.0`.


Thus, I'll be pushing up the following tags.
```
git tag -f 0.3.0 22e2cec
git tag -f 0.3.1 3e24972
git tag -f 0.3.2 e40b735
```

Thanks for your help on this. Best!
