### ISSUE TITLE
Make Semigroup superclass of Monoid.

### ISSUE THREAD

**Issue by noughtmare** [sdiehl/protolude#17]
AFAIK the only reason it's not is because of potential code breakage, but that is not a concern for this library.

It would be nice to use the `<>` operator on monoids again.

**Comment by sdiehl** [comment]
I'll look into this change. If I can do it without serious breakage I'll include it in the next point release.

**Comment by sdiehl** [comment]
The general principle I hold by in this library is that I insist on exporting the same types as the Base (see "small vehicle prelude" assumption) so that we keep compatability with existing libraries. By exporting a custom Monoid it would force everyone to use Protolude Monoid, which I don't want.

**Comment by rikvdkleij** [comment]
@sdiehl 
Is this same issue as why `<>` does not work on instance of Monoid when only importing Protolude?

When I import Prelude and Data.Monoid `<>` works.

When I import Protolude and Data.Monoid `<>` is ambiguous.

**Comment by rikvdkleij** [comment]
I'm using Protolude version 0.1.10

**Comment by sdiehl** [comment]
Monoid shouldn't be ambiguous because Protolude doesn't redefine it (it just exports the Prelude version), are you passing in `-XNoImplicitPrelude` when you launch your project or shell.

**Comment by rikvdkleij** [comment]
Issue occurs if I create instance of Monoid myself. Instance of monoids from base working okay because they are also instance of Semigroup.

Probably Protolude is missing this from Data.Monoid:

``` haskell
-- | An infix synonym for 'mappend'.
--
-- @since 4.5.0.0
(<>) :: Monoid m => m -> m -> m
(<>) = mappend 
```

**Comment by rikvdkleij** [comment]
> are you passing in -XNoImplicitPrelude when you launch your project or shell.

Yes, I have set `NoImplicitPrelude` in Cabal file

**Comment by uwap** [comment]
Yes. Same here. Not all instances of Monoid are also an instance of Semigroup which causes the problem that (<>) doesn't work on Monoids and importing it from Data.Monoid makes (<>) redundant.

**Comment by rikvdkleij** [comment]
FYI in https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Semigroup.html  :
`The use of (<>) in this module conflicts with an operator with the same name that is being exported by Data.Monoid. However, this package re-exports (most of) the contents of Data.Monoid, so to use semigroups and monoids in the same package just "import Data.Semigroup"`

**Comment by sdiehl** [comment]
Ok, I rolled it over to `Data.Monoid` as the default export in the next release.

**Comment by Profpatsch** [comment]
Want to add that I’m in favor of exporting from Semigroup. Most (if not all) modern types have a Semigroup instance, certainly everything in base.

**Comment by JustusAdam** [comment]
I'd like to chip in a bit here. 

1. I am also in favour of using the Semigroup `(<>)` particularly now that its coming to `base` also
2. I'd like to make you aware that the roll over to the Monoid `(<>)` created some real issues. Because now I have to add a whole lot of CPP again to resolve the different `(<>)` versions across the `0.1` -> `0.2` version change and presumably later again for the `0.2` -> `0.3` version change when I define my own instances of `Semigroup` and I'd like to express my profound unhappiness about that.
