### ISSUE TITLE
(.) and id from Control.Category

### ISSUE THREAD

**Issue by uwap** [sdiehl/protolude#18]
Is there any reason that the (.) and id from Control.Category is not the default?

**Comment by sdiehl** [comment]
Most Haskell code in the wild uses `(.)` from Data.Function. This is subsumed by Control.Category but I don't see any benefit from it being the default export and it will complicate type inference.

**Comment by tonyday567** [comment]
And identity instead of id.  Is this the same reasoning?

**Comment by sdiehl** [comment]
Yeah, `id` expected from Control.Category would also have to be renamed.

**Comment by sdiehl** [comment]
I don't see a reason to make this is the default export at the moment. It's only an import away via the standard Base for those who need it.
