### ISSUE TITLE
Expose `flip fmap` as `for`?

### ISSUE THREAD

**Issue by jml** [sdiehl/protolude#19]
I've seen some people discuss this on Twitter and it seems like an OK idea to me:

Expose `flip fmap` as `for`, s.t. `for :: Functor f => f a -> (a -> b) -> f b`, and expose what's currently called `for` as `forA`.

What do you think?

**Comment by sdiehl** [comment]
Not opposed to having `flip fmap` as a function but it conflicts with `for` from Data.Traversable.

``` haskell
for  :: (Applicative f, Traversable t) => t a -> (a -> f b) -> f (t b)
for = flip traverse
```

**Comment by jml** [comment]
Not up for exposing that one as `forA`? I can see why there would be significant, entirely reasonable compatibility concerns.

**Comment by sdiehl** [comment]
Little hesitant to rename something if there's already a precedent for it's name. Do you have a link to the thread in question so I can read the arguments?

**Comment by jml** [comment]
Thread starts here: https://twitter.com/snoyberg/status/758181970689994752

Thanks for considering this!

**Comment by sdiehl** [comment]
Looked at the arguments for and against this and decided that renaming for to a type that isn't subsumed by Data.Traversable.for is likely to cause some problems for users. 

I added a `foreach` function though that doesn't conflict in the namespace and has the behavior you wanted. Hopefully this is useful.

**Comment by jml** [comment]
Thank you for considering it.

**Comment by mithrandi** [comment]
`flip fmap` is nowadays `Data.Functor.(<&>)`

**Comment by sdiehl** [comment]
Yes, this is exported: https://github.com/protolude/protolude/blob/master/src/Protolude.hs#L15
