### ISSUE TITLE
Haddocks come out ugly

### ISSUE THREAD

**Issue by mitchellwrosen** [sdiehl/protolude#2]
For some reason, haddock doesn't show anything at all when you re-export a module alias like `X`: https://hackage.haskell.org/package/protolude-0.1.1/docs/Protolude.html

**Comment by mitchellwrosen** [comment]
@sdiehl if you'd like I can fix this up

**Comment by Profpatsch** [comment]
That would be nice!

**Comment by sdiehl** [comment]
Best to just work on a fix for the upstream bugs in Haddock with module reexports: https://github.com/haskell/haddock/issues/290

**Comment by mitchellwrosen** [comment]
Yikes. Ok, if anyone else wants to claim this, go ahead. My plan was just to meticulously re-export everything to appease haddock.

**Comment by sdiehl** [comment]
Routing around bugs in haddocks using hacks isn't the right answer. Closing.
