### ISSUE TITLE
example using wl-prprint-text with "import Protolude"

### ISSUE THREAD

**Issue by joe9** [sdiehl/protolude#20]
Hello,

Thanks for sharing Protolude.

Just want to check if you could kindly share the PrettyPrinter described here [http://www.stephendiehl.com/posts/strings.html](http://www.stephendiehl.com/posts/strings.html) using "import Protolude" instead of the default Prelude. 

Is there any particular reason that you chose to create your own Pretty class instead of using the Pretty provided by wl-pprint-text?

Thanks again

**Comment by sdiehl** [comment]
wl-pprint-text doesn't support automatic deriving of Show classes from generics.

**Comment by joe9** [comment]
Just want to check on the effort involved. Is it just a matter of forking wl-pprint-text and then using your Pretty class and fixing any compiling issues. Or, is there a fundamental issue which cannot be addressed?

**Comment by sdiehl** [comment]
The last part of the blog post indicates the limitation with that approach. You have to derive Generic for every datatype in your project and every datatype that previously derived Show. This is beyond the scope of Protolude and it requires changes upstream in the deriving mechanism in GHC itself and the 'text' library to be in GHC's boot libraries to be sensible replacement for base Show. The GHCI shell itself is also wired to use Show magically which I can't change.

I could however provide a TShow class in Protolude, which wouldn't be a full replacement but would be workaround. Is that what you're asking for?

**Comment by sdiehl** [comment]
Also I don't need any of the machinery in wl-pprint-text for derive Show, you just need a text-builder.

wl-pprint-text is a combiantor library for arbitrary kinds of formatting, Haskell show-style is much simpler and that's why I didn't use it in 'print'.

**Comment by joe9** [comment]
Thanks for your flexibility in offering a TShow class. My issue is that I use Text.Groom now to pretty print. I notice that when using Text, every pretty print show call is toText . groom . toString. It would be nice if I can remove that with a Text based pretty printer.

**Comment by joe9** [comment]
Just to clarify, I do not mind using toText . groom . toString when using the ghci shell. But, it does not feel right to be using that pattern when logging/pretty-printing from the program.

**Comment by sdiehl** [comment]
I think there's little I can/should do to fix this issue, until the upstream String and deriving Show get's fixed. The philosophy I take is one of just exporting existing libraries and masking deprecated and unsafe portions of base, so I can't really fix this.

**Comment by joe9** [comment]
Are you offering the TShow class in Protolude?
