### ISSUE TITLE
StringConv doesn't do UTF-8 encoding for String→ByteString

### ISSUE THREAD

**Issue by neongreen** [sdiehl/protolude#21]
For conversion between `Text` and `ByteString`, `StringConv` does UTF-8 encoding/decoding. For `String` and `ByteString`, it doesn't. Is there any good reason for this? The current behavior seems inconsistent to me (not to mention that someone might get bitten by lossy ASCII encoding).

**Comment by sdiehl** [comment]
Closed as of 0.3 refactor.
