### ISSUE TITLE
Generic `note` and `hush`?

### ISSUE THREAD

**Issue by jml** [sdiehl/protolude#22]
Our prelude has these two things:

``` haskell
-- | Generic version of 'hush' from Control.Errors
hush :: Alternative m => Either e a -> m a
hush (Left _)  = empty
hush (Right x) = pure x

-- | Generic version of 'note' from Control.Errors
note :: (MonadError e m) => e -> Maybe a -> m a
note err = maybe (throwError err) pure
```

They are inspired by functions of the same name in the [errors](https://hackage.haskell.org/package/errors-2.1.2/docs/Control-Error-Util.html) package, except more generic so I don't have to remember which spelling I want when.

I guess the former could be:

``` haskell
hush = either (const empty) pure
```

What do you think?

**Comment by tonyday567** [comment]
tryIO is an extremely useful function in that library, though throwing an ExceptionT.

**Comment by sdiehl** [comment]
All seems sensible, see if the current patch meets your needs.

**Comment by jml** [comment]
Looks good to me. Thanks.
