### ISSUE TITLE
toS from Text to ByteString adds ""

### ISSUE THREAD

**Issue by joe9** [sdiehl/protolude#29]
Hello,

Thanks for sharing Protolude.

Using toS to convert from Text to ByteString outputs this: "\"sample text here\""

whereas, using Data.String.Conversions.cs outputs this: \"sample text here\"

Is it a better idea to just export Data.String.Conversions instead instead of exporting toS?

Thanks

**Comment by sdiehl** [comment]
If you'd like to inline the logic from that library inside of `Conv.hs`, I'm happy to merge. But adding another dependency isn't on the table, at least for a alt Prelude.

**Comment by cocreature** [comment]
I’ve just taken a look at this but I’m unable to reproduce this, e.g., in GHCi I got
```
> toS ("sample text here" :: Text) :: ByteString
"sample text here"
```
which is exactly what I would expect here. @joe9 How exactly did you trigger this bug?

**Comment by sdiehl** [comment]
Yeah,  I'm not able to reproduce this either.

**Comment by sdiehl** [comment]
I think the confusion was just around the show instance inside GHCi printing double quotes. Just going to close this until we have confirmation on failure.
