### ISSUE TITLE
Including the <$> operator

### ISSUE THREAD

**Issue by LukaHorvat** [sdiehl/protolude#3]
Is there a particular reason why it isn't included?

**Comment by sdiehl** [comment]
It is:

https://github.com/sdiehl/protolude/blob/master/src/Functor.hs#L7
https://github.com/sdiehl/protolude/blob/master/src/Protolude.hs#L26

**Comment by LukaHorvat** [comment]
It's imported qualified so it doesn't get reexported as far as I can tell.

**Comment by LukaHorvat** [comment]
@sdiehl I'm just mentioning you in case you have notifications turned off on this issue. Sorry for spamming.

**Comment by sdiehl** [comment]
@LukaHorvat Sorry for the delayed response, I think you just need to pull the latest version. I'll sync Hackage with Git today.

**Comment by sdiehl** [comment]
New version is synced: https://hackage.haskell.org/package/protolude-0.1.3

Let me know if that fixes your issue.

**Comment by LukaHorvat** [comment]
As far as I know, it was fixed in the version before that. I think.
