### ISSUE TITLE
Unsatisfiable preferred version range on Hackage

### ISSUE THREAD

**Issue by glguy** [sdiehl/protolude#31]
protolude specifies an unsatisfiable "preferred" version range. Perhaps it meant to prefer the latest released version?

http://hackage.haskell.org/package/protolude/preferred/edit

**Comment by sdiehl** [comment]
I have updated this but Hackage seems to be out of date with the changes and hasn't updated in many days.

**Comment by glguy** [comment]
I just checked hackage and it was fixed, thanks!
