### ISSUE TITLE
re-use (&) from Data.Function if base >= 8.0

### ISSUE THREAD

**Issue by PierreR** [sdiehl/protolude#33]
The re-definition of `(&)` would force users of libraries that naturally re-export it from `Data.Function` (if base >= `4.8.0.0` ) to hide it from Protolude.

This is a bit annoying; while working with `protolude` together with `turtle` for instance the list of hiding items is getting long enough ;-)

Thanks for the wonderful prelude.

**Comment by sdiehl** [comment]
Yeah, this makes sense. I'll push it in the next version.
