### ISSUE TITLE
idea: liftIO1, liftIO2, liftIO3

### ISSUE THREAD

**Issue by Profpatsch** [sdiehl/protolude#38]
Lift an `IO` operation with `n` arguments into another monad.
At least 1 and 2 are helpful I think.

```haskell
liftIO1 :: MonadIO m => (a -> IO b) -> a -> m b
liftIO2 :: MonadIO m => (a -> b -> IO c) -> a -> b -> m c
liftIO3 :: MonadIO m => (a -> b -> c -> IO d) -> a -> b -> c -> m d
```

Impl from `ghc`, module `MonadUtils`:

```
-- | Lift an 'IO' operation with 1 argument into another monad
liftIO1 :: MonadIO m => (a -> IO b) -> a -> m b
liftIO1 = (.) liftIO

-- | Lift an 'IO' operation with 2 arguments into another monad
liftIO2 :: MonadIO m => (a -> b -> IO c) -> a -> b -> m c
liftIO2 = ((.).(.)) liftIO

-- | Lift an 'IO' operation with 3 arguments into another monad
liftIO3 :: MonadIO m => (a -> b -> c -> IO d) -> a -> b -> c -> m d
liftIO3 = ((.).((.).(.))) liftIO
```

**Comment by sdiehl** [comment]
What other monad would you typically be lifting this into? Is it included in the default scope of Protolude?

**Comment by Profpatsch** [comment]
> What other monad would you typically be lifting this into?

In my experience `liftIO` is a pretty common function in day-to-day programming when you are in some kind of application stack (e.g. Spock routing actions). Functions want to be lifted as well. :)

> Is it included in the default scope of Protolude?

I don’t understand, what’s the default scope of Protolude?

**Comment by sdiehl** [comment]
Like is the monad exported by default in this library or is it better served elsewhere.

I get the argument for including this in the next release. I think we can manage for the first 2. :+1:

**Comment by Profpatsch** [comment]
Ah, you mean `MonadIO`?

I think that is so basic in modern libraries, it should definitely be exported.
