### ISSUE TITLE
Consider `HasCallStack` for all trace* functions.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [sdiehl/protolude#39]
Attaching the call site with trace messages is something I think most people will find useful.

https://hackage.haskell.org/package/base-4.9.1.0/docs/GHC-Stack.html#g:2

**Comment by sdiehl** [comment]
To make this backwards compatible with 7.8 I'd have to split the whole module using preprocessor directives.

**Comment by tebello-thejane** [comment]
> To make this backwards compatible with 7.8 I'd have to **split the whole module using preprocessor directives**.

Not necessarily: https://github.com/ndmitchell/safe/issues/18#issuecomment-274458167

**Comment by sdiehl** [comment]
Ok, I like this approach. I'll roll it into the next version.

**Comment by sdiehl** [comment]
This is rolled into the pending 0.2 release.
