### ISSUE TITLE
Implementing Read instance

### ISSUE THREAD

**Issue by PierreR** [sdiehl/protolude#46]
What are the guideline about `Read` instances ?

It does not seem to be possible to do so with the provided `Read` type from Text.Read because `readsPrec` is hidden.

I am left with 
```
import GHC.Read (Read(..))
import Protolude hiding (Read)
```
which seem pretty awkward. 

Implementing such instance is required in my case so I can use https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/src/Turtle/Options.hs#L215-L216

Thanks for your support.

Cheers,

**Comment by sdiehl** [comment]
Protolude tries to avoid String functions being exported by default. Or course they're only an import away from the `Prelude` or `GHC.Read` modules if you need them or another library forces them.

**Comment by PierreR** [comment]
Your comment actually forces me to look up the `turtle` source code a bit more and I have found [a Text parsing func](https://github.com/Gabriel439/Haskell-Turtle-Library/blob/master/src/Turtle/Options.hs#L205) that I can easily use instead of a Read instance ;-)
