### ISSUE TITLE
with no `Show` instance define ability, how does one use `HUnit` ?

### ISSUE THREAD

**Issue by ababkin** [sdiehl/protolude#50]
Hi

`HUnit` relies heavily on custom types under test having `Show` instances. 
https://hackage.haskell.org/package/tasty-hunit-0.9.2/docs/src/Test-Tasty-HUnit-Orig.html#%40%3D%3F

It is of course would be great to use another printing instance like `Pretty` to output things in `Tasty`/`HUnit` but it does not look to be possible currently

The next best thing is perhaps to define `Show` instances in terms of `Pretty` locally in tests (to not taint the rest of the library with `Show`)  but then there is the `orphaned instances` problem

What is the currently suggested way of solving this problem?

Thanks

**Comment by tonyday567** [comment]
Not the best, but:

~~~
import GHC.Show (Show(..))
import Protolude hiding (show)
~~~

works.  I don't think Show instances as library api glue will be erased from haskell practice anytime soon - as much as I wish it would.  At least you're being explicit about Show usage.

**Comment by sdiehl** [comment]
@tonyday567 This is the right approach.

I can't fix all portions of the ecosystem that still rely on legacy `String`/`[Char]` if you need these bits just import the underlying `GHC.Show` and mask Protolude's version.

**Comment by ababkin** [comment]
Thanks @tonyday567 , @sdiehl 
Are you currently using a test framework that does not rely heavily on `Show` instances?
I'm all for eliminating `Show` but currently with `Tasty`/`HUnit` it seems that one has to choose between not deriving/defining `Show` instances in the library and having test coverage. And inevitably one would choose the test coverage.
Are you aware of any efforts in open source community to create a testing framework that does not rely on `Show` that I may contribute to?

**Comment by sdiehl** [comment]
I use tasty with Protolude and it works fine.

**Comment by ababkin** [comment]
Gotcha, so I assume you still define `Show` instances for all your types that you do assertions on in Tasty.
(a bit of context for this: at my company we are trying to figure out the current best practices for industrial haskell development and we are trying out the `Protolude`)

**Comment by sdiehl** [comment]
One can derive `Show` using the usual mechanisms and it maps directly to `GHC.Show`. It's just that the `show` function is masked in favor of it's polymorphic form in Protolude.

**Comment by ababkin** [comment]
thanks again for your help
