### ISSUE TITLE
(<&>) = flip (<$>)

### ISSUE THREAD

**Issue by Profpatsch** [sdiehl/protolude#53]
We already have

```
(&) = flip ($)
```

so I think `<&>` would be a nice logical completion. Especially for use cases like

```
somefunctor <&> function >>= \case
  pattern-match
```

Of course there’s `foreach`, but the naming is kind of questionable, especially combined with `for` from `Traversable`. For example, I have a [piece of code](https://github.com/Profpatsch/blog/commit/04f27de2dff4b63c631dfe31fd19d4f9f842013a#diff-40bcfa35e53fa048ff2f7915fe65fd5dR40) where the levels are becoming confusing:

```
metas <- for (foreach postDirs (FP.</> postFileName)) postToPostMeta
```

```
metas <- for (postDirs <&> (FP.</> postFileName)) postToPostMeta
```

looks nicer to me. Not much, but at least a bit. Hm, maybe I should just go with

```
metas <- for (postDirs `foreach` (FP.</> postFileName)) postToPostMeta
```

Another valid stance would be to *not* have `<&>` or even `&` because it’s just confusing code flow even more.

**Comment by sdiehl** [comment]
Makes sense.

**Comment by phadej** [comment]
FWIW `<&>` has `infixl 1` in `lens` (where from many use it). It's way better to have same infixity as `>>=`. `infixl4` is too tight.

**Comment by Profpatsch** [comment]
> It's way better to have same infixity as >>=. infixl4 is too tight.

Can you support that claim?

`<&>` is supposed to replace `<$>`. `<$>` has `infixl 4`, so the following is valid without parentheses:

```haskell
maybeFoo <&> fooFieldAccessorMeh >>= \case
  Just meh -> …
  Nothing -> …
```

leading to a natural flow from left to right.

Compare `($)` and `(&)`:

```
Prelude Data.Function> :i (&)
(&) :: a -> (a -> b) -> b 	-- Defined in ‘Data.Function’
infixl 1 &
Prelude Data.Function> :i ($)
($) ::
  forall (r :: GHC.Types.RuntimeRep) a (b :: TYPE r).
  (a -> b) -> a -> b
  	-- Defined in ‘GHC.Base’
infixr 0 $
```

The difference of 1 is probably to support usage of `(&)` inside `($)`.

**Comment by llelf** [comment]
To save you from bikeshedding: it will be in base (4.11) with `infixl 1`

**Comment by Profpatsch** [comment]
After experimenting a bit in the repl, it seems like chaining works for the same fixity, if both operators bind in the same direction, so the initial use-case still works for `infixl 1 <&>`.

**Comment by sdiehl** [comment]
Should be fixed on https://github.com/sdiehl/protolude/commit/243a309bc1d02ce76f0793a4a439553ee43b01ab  Defaults to using the symbol provided by Base 4.11 if it exists, otherwise provides a shim.
