### ISSUE TITLE
Why does `maybeToEither` have type `Monoid b => (a -> b) -> Maybe a -> b`?

### ISSUE THREAD

**Issue by matthew-piziak** [sdiehl/protolude#54]
`Either` doesn't even have a `Monoid` instance.

I can see `maybe mempty` being a useful function, particularly when mapping `Semigroup a => Maybe a` to a target `Monoid b => b` through `a -> b`, but I don't know why it has this name when it can't even _return_ `Either` types.

**Comment by sdiehl** [comment]
Fixed in c2570f7 . Hopefully that makes more sense.

**Comment by matthew-piziak** [comment]
That makes more sense. It's exactly what behavior I'd expect from the
function names. Thank you for the change!

**Comment by sdiehl** [comment]
No worries, thanks for letting me know. :+1:
