### ISSUE TITLE
Proposal: Add safe-exceptions package to Protolude dependencies

### ISSUE THREAD

**Issue by roman** [sdiehl/protolude#59]
Hi Stephen,

First of all, I would like to thank you for building this library, I started to heavily use it since [your comments](https://twitter.com/smdiehl/status/729693541014757376) and [blogpost](http://www.stephendiehl.com/posts/protolude.html) around why you implemented it (totally agree). I've stopped using the default prelude in all my personal projects and it has made a huge improvement in the way I do Haskell these days.

I've found another library around execeptions that brings me a similar experience to Protolude, the library is called [safe-exceptions](https://hackage.haskell.org/package/safe-exceptions-0.1.6.0), it's [announcement blogpost](https://www.fpcomplete.com/blog/2016/06/announce-safe-exceptions) goes through good explanations around why I would like to use in a "production" setting rather than relying on the default APIs.

Would you be open to include this as the Protolude default for exceptions API? If not, would you like to expand on your rationale? I'm very interested in hearing your thoughts on the matter.

Thanks for your time.

**Comment by sdiehl** [comment]
Is there a reason we couldn't just use this in conjunction with Protolude, are there any conflicting exports that prevent or hinder it's use?

**Comment by roman** [comment]
> are there any conflicting exports that prevent or hinder it's use?

Sadly, no, here is the list of some of the functions:

* `throwIO` 
* `finally`
* `catch` 
* `handle`

This are a few of them, haven't gone through the whole duplicated list... the functions behaves somewhat the same, some of them make it explicit to handle async exceptions (e.g. `catchAny`) instead of always doing it. Also they use the `MonadThrow` typeclass from the `exceptions` package.

**Comment by sdiehl** [comment]
My question was more around the fact that _since_ there are so many different opinions on error handling just let end users pull in the library that fits their needs. I'm not sure this prelude needs to have a strong opinion on this.

**Comment by roman** [comment]
Ahhh, gotcha...

Fair point, I normally go with [fpco](https://github.com/fpco) or [commercialhaskell](https://github.com/commercialhaskell) projects whenever I'm working on stuff that I would consider production material;  it makes total sense not to enforce this opinion on everybody else though.

Given there is a lot of ways of going around this, I will stop pursuing this ticket then, closing now. 

Perhaps would be nice to share the possible exception woes on the documentation and point to informed blogposts to allow users to make better decisions around that? If you think this is a good idea I would love to help you write it down on what you consider the appropriate place for it.

Thanks for the prompt replies.

**Comment by sdiehl** [comment]
@roman Sure, if you'd like to extend the README just submit a PR.
