### ISSUE TITLE
Propose putErrLn (or a better name)

### ISSUE THREAD

**Issue by PierreR** [sdiehl/protolude#66]
Because working with `hPutStrLn stderr` requires a type annotation most of the time, I would like to propose the addition of 
```
putErrLn ::  MonadIO m => Handle -> a -> m ()
putErrLn = hPutStrLn stderr
``` 
along
```
hPutStrLn :: MonadIO m => Handle -> a -> m ()
```
https://github.com/sdiehl/protolude/blob/master/src/Protolude/Show.hs#L37

This is quite similar to `Debug.Trace.traceIO`.

Would you be OK with that ? If so, is there a better name than `putErrLn` ?

**Comment by sdiehl** [comment]
Indeed, this sounds like a good proposal. :+1:

**Comment by PierreR** [comment]
Is it better to provide ´putErr` only as I have in the PR or the whole set: `putTErr`, `putLTErr`, putBErr` ...
If I provide the sole `puErr`, `putTErr` might still be a better name ?
