### ISSUE TITLE
Neither undefined or error raise compiler warnings on usage

### ISSUE THREAD

**Issue by timmot** [sdiehl/protolude#69]
From README.md:
> Partial functions like `undefined` and `error` raise compiler warnings on usage.

> This is by design. For fatal uncatchable errors use the provided panic function if you intend the program to immediately abort.

Has this intentionally been removed or should warning pragmas be attached to these functions?

**Comment by sdiehl** [comment]
This wasn't migrated after we changed to the new cross GHC error handling. I'm not opposed to adding it back in.

**Comment by sdiehl** [comment]
Ok, merged the pull request for this. Thanks!
