### ISSUE TITLE
[Question] fail method not exposed ?

### ISSUE THREAD

**Issue by PierreR** [sdiehl/protolude#71]
What's the idiomatic way to handle call to the `fail` method from the Monad interface ?

It is not exposed by `protolude` and it is not quite clear to me if it is always a good idea to replace the call with `panic` (particularly in parser logic).

Thanks for your help.

**Comment by sdiehl** [comment]
Per the MonadFail proposal, `fail` was removed as the last warty bit of the old Monad class. The preferred replacement would be using Parsec [`parserFail`](https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec-Prim.html#v:parserFail) or adding a [`Control.Monad.Fail`](https://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Monad-Fail.html) constraint. Or as a fallback just pulling the fail method from the baes prelude: `import Control.Monad (fail)`.

Like most things in Protolude, we're just offering an idiomatic default. If you need to work with legacy code the Prelude is also just an import away.

**Comment by PierreR** [comment]
Thanks for your input ;-)

**Comment by PierreR** [comment]
In that regard, would it be a good idea to expose the "MonadFail" type class in `protolude` ?

**Comment by sdiehl** [comment]
Most modern Haskell isn't really going to use ``fail`` too frequently, so I don't see the use in exporting it by default. Since it's only a ``import Control.Monad.Fail`` import away, I think users who need it should be all set with manually importing it.
