### ISSUE TITLE
ExceptT constructor

### ISSUE THREAD

**Issue by Profpatsch** [sdiehl/protolude#75]
Any reason why the `ExceptT` constructor is not exported? As far as I can see, it’s the only way to conveniently go from `Either` to `ExceptT`.

**Comment by sdiehl** [comment]
I believe it is: https://github.com/sdiehl/protolude/blob/c9a2d176d144c4e9ac3a11668706e5f0c11ec0bf/src/Protolude.hs#L293

**Comment by Profpatsch** [comment]
Ah, then I probably looked at the wrong package or commit. What about `withExcept(T)` and `mapExcept(T)`? They shouldn’t clash with anything else and since it’s a monad transformer they are the only way to modify the exception value.

**Comment by sdiehl** [comment]
Don't see any issue with adding them. We already export `withState`. :+1:
