### ISSUE TITLE
While I agree that `head` is partial, overloading it has lead to surprising behavior

### ISSUE THREAD

**Issue by ababkin** [sdiehl/protolude#78]
consider this test from a practical project:
```
    it "calculates complex case correctly" $ do
      let rows = length grid
          cols = length (head grid)
          grid :: [[Double]] =
                  [ [1.0,   2.0]
                  , [2.0,   3.0]
                  , [-2.0,  1.0]
                  , [0,     0  ]
                  ]
      (rows, cols) `shouldBe` (4, 2)
```
it fails with:
```
       expected: (4,2)
       but got: (4,1)
```
After scratching head for several minutes, that this is because the type signature has changed, but I say this is very surprising behavior that is undesirable. 
I'm curious why `head` was reintroduced (and hasn't stayed being `headMay`) yet changed its signature for the safe one?

**Comment by sdiehl** [comment]
The behavior exhibited here concerns the foldable instance of ``Maybe`` which many people have had discussions whether it should exist.

```haskell
λ> length (Just 3)
1
```

But this is currently the expected behavior exposed by base class instances, so Protolude isn't going to revisit this issue.

**Comment by ababkin** [comment]
Thanks for the reply Stephen.
Having a foldable instance for `Maybe` makes sense to me.
What rubs me the wrong way is changing the typesig on `head`, which can lead to tricky to find bugs (like what I've outlined above) where the type checker is unable to save us.
My suggestion is to just not export `head`, so one would consciously be aware of the different type when explicitly changing `head` to `headMay` in their code.

**Comment by sdiehl** [comment]
The goal of the project is not to be backwards compatible. The migration path will involve name changes and some understanding of how it differs from the default Prelude. Being drop-in compatible would not work.

**Comment by sdiehl** [comment]
The "safest" solution for migrating code using the legacy prelude is to replace instances of `head` with [`unsafeHead`](https://hackage.haskell.org/package/protolude-0.2.1/docs/Unsafe.html#v:unsafeHead) which has the same partiality if you want this.
