### ISSUE TITLE
Releasing  0.2.2

### ISSUE THREAD

**Issue by PierreR** [sdiehl/protolude#84]
Do you know when `0.2.2` is going to land on hackage ? 
Just asking because it prevents our (ghc-8.4.1) [travis-test](https://travis-ci.org/bartavelle/language-puppet/jobs/359336678) to succeed.

Cheers,

**Comment by sdiehl** [comment]
I will do it this afternoon, thanks for the heads up.

**Comment by sdiehl** [comment]
It is uploaded: https://hackage.haskell.org/package/protolude-0.2.2

Cheers
