### ISSUE TITLE
stackage nightly

### ISSUE THREAD

**Issue by tonyday567** [sdiehl/protolude#85]
Can we get protolude back on the nightly's please 🥇 

Just have to remove this line I think.

https://github.com/fpco/stackage/blob/26723c68210736df9c28acf383a3aaaf3c24eb3b/build-constraints.yaml#L3695

**Comment by sdiehl** [comment]
As far as I can tell there are no active build or bound problems with protolude-0.2.2 so if the FPCO folks dropped in the Stack nightlies you'll have to report it upstream.

**Comment by tonyday567** [comment]
https://www.stackage.org/lts-11.3/package/protolude-0.2.2

A lot of packages were dropped (by stack dudes) a few weeks ago, when nightlies moved to 8.4.  You'll see in the stackage link that protolude is 0.2.1 in the nightlies (but still being updated fine for lts which is ghc 8.2), and the last nightly it was in was 2018-03-12 (the last of the 8.2s).

See: https://github.com/fpco/stackage/issues/3389

**Comment by sdiehl** [comment]
Ok I have a pull request in flight which should fix the issue.
https://github.com/fpco/stackage/pull/3478

**Comment by sdiehl** [comment]
As a stop-gap adding `protolude-0.2.2` from Hackage to your `extra-deps` should also be fine for GHC 8.4.

**Comment by sdiehl** [comment]
The fix is landed upstream, I think tonight's build should have it fixed.

**Comment by tonyday567** [comment]
perfect. thanks!
