### ISSUE TITLE
Recommended hlint rules?

### ISSUE THREAD

**Issue by jml** [sdiehl/protolude#89]
I've been exploring enforcing [hlint](https://github.com/ndmitchell/hlint#readme) checks with CI on my Haskell projects. One of the first issues I hit is that hlint thinks `id x` is redundant, whereas in my Protolude projects, `id x` is often quite meaningful and it's `identity x` that would be redundant.

Conversely, I think there might be hlint suggestions that could be made if it knew that Protolude was being imported.

Are there a set of hlint rules for Protolude already extant & could they be shared with the wider community?

**Comment by ndmitchell** [comment]
Awesome! Want to include them in HLint itself? You can put groups, e.g: https://github.com/ndmitchell/hlint/blob/master/data/hlint.yaml#L648 - disabled by default, and then people who want to use protolude can just enable the group.

**Comment by sdiehl** [comment]
Yeah, this might be best to submit upstream if @ndmitchell is cool with this.

**Comment by jml** [comment]
Will do so. I can only think of the `id` => `identity` thing for now, but I guess I (or others) can always send follow-up PRs as they discover protolude-inspired suggestions.
