### ISSUE TITLE
It's not in stackage

### ISSUE THREAD

**Issue by alexanderkjeldaas** [sdiehl/protolude#9]
Would be great to have it there..

**Comment by sdiehl** [comment]
https://github.com/fpco/stackage/pull/1370

**Comment by sdiehl** [comment]
There's some unrelated build problem upstream in Stackage. Check back in a day or two it should be uploaded.

**Comment by alexanderkjeldaas** [comment]
Thanks! :+1:

**Comment by sdiehl** [comment]
Ok it's merged upstream into stackage nightly. Check back at midnight.

**Comment by sdiehl** [comment]
Ok it's in the nightly release now: https://www.stackage.org/nightly-2016-04-18/package/protolude-0.1.3
 use:

```
--resolver nightly-2016-04-18
```

**Comment by alexanderkjeldaas** [comment]
Yes, I'm using it in the latest build.  Thanks!
