### ISSUE TITLE
Potential unsafety of Data.Text.IO functions

### ISSUE THREAD

**Issue by jkachmar** [sdiehl/protolude#99]
It looks as if the file operation functions that `protolude` uses are just re-exports from `Data.Text.IO`:

https://github.com/sdiehl/protolude/blob/5024f3fef98ab01d4b8d35728982cc38b10de53f/src/Protolude.hs#L424-L429

A few years back [Michael Snoyman wrote a post about this](https://www.snoyman.com/blog/2016/12/beware-of-readfile) and included recommendations to use something like `fmap (decodeUtf8With lenientDecode)` around functions from `Data.ByteString`.

Is there a benefit to keeping the behavior from `Data.Text.IO`? From my perspective as a user it feels like an uncomfortably easy footgun to have around by default.

**Comment by sdiehl** [comment]
Closed as of 0.3 refactor.
